language:
- php
- node_js
php:
- 7.1
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy:
- echo 'Successfully deployed to AWS'
env:
  global:
    secure: D/qfqsW0DMSjYc+1mrUyjyq/3kHdzUsNl7DDEJIFrkxKc5FUFQfnWdSpX6o7oX7RMhX2oQM53BMCttTOFikTYjORRNDqCAo21JyUfzoj0dtBuJ3AsclXiNX51iZGFXAzEszBZjjMtKkvkVMJM1mXZC2Gix9aIKGocDZ4aIPuPb7nIJIy4A5IBIkLeFoUoJtK4hAjQFTowLj4tm0xy9R2Vp6QP1is5lrM8zzCgLOPNTK9PkSX8IwCNXxmnal2RuRB+LwMFcxCCc5ESepQ58i2vmIor1XK5tYz+LzZjU8GMpjLJWCw9TTfVIJLlzzV6K+DWWzna24vh2POaguLF1VEcOONLc6oNZjTqn+IjUREXd2q943VTgCZA+cq7YGzIzNNq92h7j3UKgnDz6xC8G9Eh3vy3Qdgn5eTrq7yrHSy+e2SbHwovxts1AEaQTPjGXhjw0fOw5ldNu0S9+PUUi+HCWSn20wm+JPWA9qtgTgisGWbUSDxJWjFfYoeu7rejayCaRZW6iClWiC7bJRlowoWXf1xF7dDP6RlYaUK0IeNFTYoVgG5LmLU5oKRYZlMYN6mNUxlhdaacy7jwWh6Q1MBveE0PAnJVFm7LwGlnh6gQ46b4Xh6dNYTo5x5mOcP/qZmV58KVkFJRZ9HPIA3iyarm4onqdMeY/QjL5kOqNEq+n4=
