services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: [ '8000:8000' ]
    volumes:
      - .:/var/task
    env_file:
      - ./.env
      - ./config/local.env
    environment:
      HANDLER: index.php
      DOCUMENT_ROOT: .
