name: Deploy
on:
  push:
    branches:
      - php8-update
  pull_request:
    branches:
      - php8-update
jobs:
  deploy-lambda-qa:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: PWD
        run: ls /app

      - name: Install dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "./composer.json"
        with:
          php_version: "8.3"
          version: "2.5.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer Install
        run: composer install

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Coveralls
        run: vendor/bin/coveralls -v

      - name: PHPCS
        run: vendor/bin/phpcs -n --standard=PSR1,PSR2 src/

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 946183545209.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: itemservice-qa
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:qa-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:qa-latest

      - name: Update Lambda
        run: |
          aws lambda update-function-code --function-name=ItemService-qa-new --image-uri=946183545209.dkr.ecr.us-east-1.amazonaws.com/itemservice-qa:qa-latest --region us-east-1
